apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-service
  template:
    metadata:
      labels:
        app: quote-service
    spec:
      containers:
        - name: quote-service
          image: quote-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: mongodb://mongo-quote-service:27017/mydb
            - name: JWT_SECRET
              value: QixCfDroNQPOz2UtTqrlryLHQeQv4Fl7nk/1FJp0KNM=
